apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: kargo-demo
spec:
  promotionPolicies:
    - stage: test
      autoPromotionEnabled: true
    # - stage: uat
    #   autoPromotionEnabled: true
