apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: pre-prod
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: silly-demo
    sources:
      stages:
      - test
  promotionTemplate:
    spec:
      steps:
      - uses: git-clone
        config:
          repoURL: https://github.com/vfarcic/kargo-demo
          checkout:
          - branch: main
            path: ./src
          - branch: stage/pre-prod
            create: true
            path: ./out
      - uses: git-clear
        config:
          path: ./out
      - uses: kustomize-set-image
        as: update-image
        config:
          path: ./src/kustomize/base
          images:
          - image: ghcr.io/vfarcic/silly-demo
      - uses: kustomize-build
        config:
          path: ./src/kustomize/overlays/pre-prod
          outPath: ./out/manifests.yaml
      - uses: git-commit
        as: commit
        config:
          path: ./out
          messageFromSteps:
          - update-image
      - uses: git-push
        config:
          path: ./out
          targetBranch: stage/pre-prod
      - uses: argocd-update
        config:
          apps:
          - name: silly-demo-pre-prod
            sources:
            - repoURL: https://github.com/vfarcic/kargo-demo
              desiredCommitFromStep: commit
